name: Harley Test
favicon: null
layout_spectrum: 0.9399861462879926
typography_spectrum: 0.9065921604633331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0706'
    - '#50382b'
    - '#d0c4b6'
    - '#866643'
    - '#ebeedd'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.7067721765488386
  rhythmicContrast: 0.30667390837334096
purpose: []
